// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoApi.Driven.DomainDb;

#nullable disable

namespace TodoApi.Driven.DomainDb.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20251117172019_UpdatePasswordHashLength")]
    partial class UpdatePasswordHashLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TodoApi.Domain.UserAggregate.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TodoApi.Domain.UserAggregate.Entities.User", b =>
                {
                    b.OwnsOne("TodoApi.Domain.UserAggregate.ValueObjs.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(54)
                                .HasColumnType("character varying(54)")
                                .HasColumnName("PasswordHash");

                            b1.Property<string>("SaltStr")
                                .IsRequired()
                                .HasMaxLength(34)
                                .HasColumnType("character varying(34)")
                                .HasColumnName("PasswordSalt");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("PasswordHash")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
